{{- if eq (include "victorialogs.vmauthEnabled" .) "true" }}
{{- $config := include "victorialogs.vmauthConfig" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "victorialogs.vmauthFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "victorialogs.vmauthLabels" . | nindent 4 }}
type: Opaque
data:
  auth.yml: {{ $config | b64enc | quote }}
{{- end }}
