[FILTER]
    Name         lua
    Match_regex  ^(?!out_(audit|k8s_event|nginx|access|int|pods|system|default)$).*
    script       /fluent-bit/etc/update_level_syslog.lua
    call         update_level
