[FILTER]
    Name         lua
    Match        *
    script       /fluent-bit/etc/update_level_syslog.lua
    call         update_level

# Copy level to detected_level for logql to logsql converter
[FILTER]
    Name                modify
    Match               *
    Copy                level       detected_level
