version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    actions-deps:
      patterns:
        - "*"
# Go mod bot configurations
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    k8s.io:
      patterns:
      - "k8s.io/*"
    go.opentelemetry.io:
      patterns:
      - "go.opentelemetry.io/*"
  open-pull-requests-limit: 20
# Docker bot configurations
- package-ecosystem: "docker"
  directories:
  - "/"
  - "/integration-tests"
  schedule:
    interval: "monthly"
  groups:
    docker-deps:
      patterns:
        - "*"
