{{- if .Values.graylog.install }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "logging.labels" (dict "ctx" . "name" "mongo-claim" "component" "graylog") | nindent 4 }}
    {{- if .Values.graylog.labels }}
    {{- include "logging.extraLabels" (dict "ctx" . "extraLabels" .Values.graylog.labels) | nindent 4 }}
    {{- end }}
  {{- if .Values.graylog.annotations }}
  annotations:
    {{- toYaml .Values.graylog.annotations | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512M
  {{- if .Values.graylog.mongoPersistentVolume }}
  volumeName: {{ .Values.graylog.mongoPersistentVolume }}
  {{- end }}
  {{- if .Values.graylog.mongoStorageClassName }}
  storageClassName: {{ .Values.graylog.mongoStorageClassName }}
  {{- else if .Values.graylog.mongoPersistentVolume }}
  storageClassName: ""
  {{- end }}
{{- end }}
