sonar.sources=.
sonar.exclusions=**/*_test.go,api/v1/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.language=go
sonar.sourceEncoding=UTF-8

# Exception for http protocol in victorialogs URL. It's sufficient for tests workflow.
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=githubactions:S5332
sonar.issue.ignore.multicriteria.e1.resourceKey=.github/workflows/integration-tests.yml
