{{- if .Values.createClusterAdminEntities }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}-logging-operator
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "logging.labels" (dict "ctx" . "name" (printf "%s-logging-operator" .Release.Namespace) "component" "logging-operator") | nindent 4 }}
    {{- include "logging.extraLabels" . | nindent 4 }}
rules:
  # Need to get list of nodes and them runtimes to discover which runtime type should use
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
{{- end }}
