apiVersion: v1
kind: ServiceAccount
metadata:
  name: logging-service-operator
  labels:
    {{- include "logging.labels" (dict "ctx" . "name" "logging-service-operator" "component" "logging-operator") | nindent 4 }}
    {{- include "logging.extraLabels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
