apiVersion: v1
kind: Service
metadata:
  name: logging-fluentbit
  namespace: {{ .Release.Namespace }}
  labels:
    name: logging-fluentbit
    app.kubernetes.io/name: logging-fluentbit
    app.kubernetes.io/component: fluentbit
    app.kubernetes.io/part-of: logging
    app.kubernetes.io/managed-by: logging-operator
    component: logging-fluentbit
{{- if .Values.OpenshiftDeploy }}
    provider: openshift
{{- else }}
    provider: kubernetes
{{- end }}
spec:
  selector:
    name: logging-fluentbit
  ports:
    - name: logging-fluentbit
      port: 2020
      protocol: TCP
      targetPort: 2020
{{- if and .Values.Fluentbit.Output.Prometheus.Enabled .Values.Fluentbit.Output.Prometheus.Port }}
    - name: metrics
      port: {{ .Values.Fluentbit.Output.Prometheus.Port }}
      protocol: TCP
      targetPort: {{ .Values.Fluentbit.Output.Prometheus.Port }}
{{- end }}
