{{/* Can be used only for deployment in Kubernetes <1.25 */}}
{{- if .Capabilities.APIVersions.Has "policy/v1beta1" }}
  {{- if .Values.createClusterAdminEntities }}
    {{- if .Values.fluentbit.install }}
      {{- if .Values.fluentbit.securityResources.install }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Values.fluentbit.securityResources.name }}
  annotations:
    kubernetes.io/description: {{ .Values.fluentbit.securityResources.name }} psp is used for the fluentbit daemonset
  {{- if .Values.fluentbit.annotations }}
    {{- toYaml .Values.fluentbit.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "logging.labels" (dict "ctx" . "name" .Values.fluentbit.securityResources.name "component" "fluentbit") | nindent 4 }}
    {{- if .Values.fluentbit.labels }}
    {{- include "logging.extraLabels" (dict "ctx" . "extraLabels" .Values.fluentbit.labels) | nindent 4 }}
    {{- end }}
spec:
  privileged: {{ .Values.fluentbit.securityContextPrivileged }}
  allowPrivilegeEscalation: {{ .Values.fluentbit.securityContextPrivileged }}
  {{- if not .Values.fluentbit.securityContextPrivileged }}
  requiredDropCapabilities:
    - ALL
  allowedCapabilities:
    - DAC_OVERRIDE
  {{- end }}
  # Allow core volume types.
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
    - 'hostPath'
  allowedHostPaths:
    - pathPrefix: "/etc/sysconfig/docker"
      readOnly: true
    - pathPrefix: "/etc/docker/daemon.json"
      readOnly: true
    - pathPrefix: "/etc/hostname"
      readOnly: true
    - pathPrefix: "/var/log"
      readOnly: true
    - pathPrefix: "/var/lib/docker/containers"
      readOnly: true
    {{- if or (eq .Values.fluentbit.storageProfile "persistent-offsets") (eq .Values.fluentbit.storageProfile "node-persistent") }}
    - pathPrefix: "/var/lib/fluent-bit/state"
    {{- end }}
    {{- if eq .Values.fluentbit.storageProfile "node-persistent" }}
    - pathPrefix: "/var/lib/fluent-bit/storage"
    {{- end }}
    - pathPrefix: "/fluent-bit/etc"
      readOnly: true
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    # Permits the container to run with root privileges as well.
    rule: 'RunAsAny'
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Allow adding the root group.
      - min: 0
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Allow adding the root group.
      - min: 0
        max: 65535
  readOnlyRootFilesystem: true
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
