[FILTER]
    Name         modify
    Match        system.systemd
    Hard_rename  MESSAGE log

[FILTER]
    Name         modify
    Match_Regex  ^(audit[.]var[.]l(og|ib)[.](openshift-apiserver|kube-apiserver|kubernetes[.]audit|kubernetes[.]kube-apiserver|origin[.]ocp-audit)).*
    Condition    Key_does_not_exist log
    Add          log (message)

[FILTER]
    Name         modify
    Match_Regex  ^(audit[.]var[.]l(og|ib)[.](openshift-apiserver|kube-apiserver|kubernetes[.]audit|kubernetes[.]kube-apiserver|origin[.]ocp-audit)).*
    Copy         log  short_message

# Added short_message condition as in case of http output enabled and stream routing enabled,
# all processed records are reemitted to the pipeline start with new tags and they don't have log field but have short_message
[FILTER]
    Name         modify
    Match_Regex  ^(?!audit[.]var[.]l(og|ib)[.](openshift-apiserver|kube-apiserver|kubernetes[.]audit|kubernetes[.]kube-apiserver|origin[.]ocp-audit)).*
    Condition    Key_Does_Not_Exist log
    Condition    Key_Does_Not_Exist short_message
    Set          log ""

[FILTER]
    Name         grep
    Match_Regex  ^(?!audit[.]var[.]l(og|ib)[.](openshift-apiserver|kube-apiserver|kubernetes[.]audit|kubernetes[.]kube-apiserver|origin[.]ocp-audit)).*
    Logical_Op   or
    Exclude      log \A\s*\z
    Exclude      short_message \A\s*\z
