{{- if .Values.fluentbit.install }}
{{- if .Values.fluentbit.aggregator }}
{{- if .Values.fluentbit.aggregator.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logging-fluentbit-aggregator
  labels:
    {{- include "logging.labels" (dict "ctx" . "name" "logging-fluentbit-aggregator" "component" "fluentbit") | nindent 4 }}
    {{- if .Values.fluentbit.labels }}
    {{- include "logging.extraLabels" (dict "ctx" . "extraLabels" .Values.fluentbit.labels) | nindent 4 }}
    {{- end }}
  {{- if .Values.fluentbit.annotations }}
  annotations:
    {{- toYaml .Values.fluentbit.annotations | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
