{{- if and .Values.fluentd.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logging-fluentd
  labels:
    {{- include "logging.labels" (dict "ctx" . "name" "logging-fluentd" "component" "fluentd") | nindent 4 }}
    {{- if .Values.fluentd.labels }}
    {{- include "logging.extraLabels" (dict "ctx" . "extraLabels" .Values.fluentd.labels) | nindent 4 }}
    {{- end }}
  {{- if .Values.fluentd.annotations }}
  annotations:
    {{- toYaml .Values.fluentd.annotations | nindent 4 }}
  {{- end }}
{{- end }}
