---
quiet: true
skip-check:
- CKV_K8S_15 # Image Pull Policy should be Always
- CKV_K8S_21 # The default namespace should not be used. (This rule not best practices: https://github.com/bridgecrewio/checkov/issues/3910)
- CKV_K8S_43 # Image should use digest. (Requires a common target approach)
- CKV_GHA_2 # Ensure run commands are not vulnerable to shell injection.
- CKV_GHA_7 # The build output cannot be affected by user parameters other than the build entry point and the top-level source location. GitHub Actions workflow_dispatch inputs MUST be empty
- CKV2_K8S_6 # Minimize the admission of pods which lack an associated NetworkPolicy. (This is a limitation of the tool, not a bug in the manifests)
- CKV2_GHA_1 # Ensure top-level permissions are not set to write-all. (It is not possible to reduce the minimum rights for third-party services)
