{
 "title": "FluentBit v1",
 "description": "Dashboard shows FluentBit's metrics about its work using metrics from /v1 metrics endpoint",
 "tags": [
  "logging",
  "fluent-bit"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(fluentbit_uptime{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(fluentbit_uptime{cluster=\"$cluster\", namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "inter",
    "query": "30s,1m,2m,5m,10m,30m,1h,2h,5h,10h,1d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active pods",
   "type": "stat",
   "description": "Show count of active FluentBit pods in selected namespace",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(fluentbit_uptime{cluster=\"$cluster\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total input bytes",
   "type": "stat",
   "description": "Show total count of bytes which FluentBit read or received any other ways. Total calculate as summary by all pods and all inputs for selected namespace.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total input records/s",
   "type": "stat",
   "description": "Show total records which FluentBit read or received any other ways. Total calculate as summary by all pods and all inputs for selected namespace.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "r/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total{cluster=\"$cluster\", namespace=\"$namespace\"}[2m]))"
    }
   ]
  },
  {
   "title": "Total output bytes",
   "type": "stat",
   "description": "Show total count of bytes which FluentBit sent to any endpoints. Total calculate as summary by all pods and all outputs for selected namespace.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total output records/s",
   "type": "stat",
   "description": "Show total records which FluentBit sent to any endpoints. Total calculate as summary by all pods and all outputs for selected namespace.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "r/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total{cluster=\"$cluster\", namespace=\"$namespace\"}[2m]))"
    }
   ]
  },
  {
   "title": "Total retries/s",
   "type": "stat",
   "description": "Show total count of retries which FluentBit execute to send logs in configured outputs. Total calculate as summary by all pods for selected namespace.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_retries_total{cluster=\"$cluster\", namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total errors/s ",
   "type": "stat",
   "description": "Show total count of errors in FluentBit during read, parse or send logs. Total calculate as summary by all pods for selected namespace.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_errors_total{cluster=\"$cluster\", namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Show maximum version among all FluentBit pods in selected namespace.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(fluentbit_build_info{cluster=\"$cluster\", namespace=\"$namespace\"}) by (version)",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Build info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "FluentBit info",
     "type": "table",
     "description": "Show information about version, edition and uptime for all FluentBit pods in selected namespace",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "fluentbit_uptime{cluster=\"$cluster\", namespace=\"$namespace\"}",
       "legendFormat": "Uptime"
      },
      {
       "expr": "process_start_time_seconds{cluster=\"$cluster\", namespace=\"$namespace\", container=~\".*fluentbit.*\"} * 1000",
       "legendFormat": "Start time"
      },
      {
       "expr": "fluentbit_build_info{cluster=\"$cluster\", namespace=\"$namespace\"}",
       "legendFormat": "Build info"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input bytes/s",
     "type": "timeseries",
     "description": "Show how much bytes FluentBit read or received",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(fluentbit_input_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (namespace, pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Output bytes/s",
     "type": "timeseries",
     "description": "Show how much bytes FluentBit sent to any outputs",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(fluentbit_output_proc_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (namespace, pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Input",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input records",
     "type": "timeseries",
     "description": "Show how much records FluentBit read or received from any sources",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "r/s" } },
     "targets": [
      {
       "expr": "sum(rate(fluentbit_input_records_total{cluster=\"$cluster\", namespace=\"$namespace\"}[2m])) by (namespace, pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Files opened",
     "type": "timeseries",
     "description": "Show how much files FluentBit open to read logs",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "sum(idelta(fluentbit_input_files_opened_total{cluster=\"$cluster\", namespace=\"$namespace\"}[2m])) by (namespace, pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Files closed",
     "type": "timeseries",
     "description": "Show much files FluentBit closed after complete read logs from these files",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "targets": [
      {
       "expr": "sum(idelta(fluentbit_input_files_closed_total{cluster=\"$cluster\", namespace=\"$namespace\"}[2m])) by (namespace, pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Files rotated",
     "type": "timeseries",
     "description": "Show how much files which FluentBit reads were rotated",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
     "targets": [
      {
       "expr": "sum(idelta(fluentbit_input_files_rotated_total{cluster=\"$cluster\", namespace=\"$namespace\"}[2m])) by (namespace, pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filter added records",
     "type": "timeseries",
     "description": "Show how much records were added with using filters in FluentBit",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "r/s" } },
     "targets": [
      {
       "expr": "sum(rate(fluentbit_filter_add_records_total{cluster=\"$cluster\", namespace=\"$namespace\"}[2m])) by (namespace, pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Filter emitted records",
     "type": "timeseries",
     "description": "Show how much records were emitted with using filters in FluentBit.\nThe `Emitter` is an internal FluentBit plugin that allows other components of the pipeline to emit custom records. On this case `rewrite_tag` creates an Emitter instance to use it exclusively to emit records, on that way we can have a granular control of who is emitting what.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "r/s" } },
     "targets": [
      {
       "expr": "sum(rate(fluentbit_filter_emit_records_total{cluster=\"$cluster\", namespace=\"$namespace\"}[2m])) by (namespace, pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Filter dropped records",
     "type": "timeseries",
     "description": "Show how much records were dropped during processing records in FluentBit",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "r/s" } },
     "targets": [
      {
       "expr": "sum(rate(fluentbit_filter_drop_records_total{cluster=\"$cluster\", namespace=\"$namespace\"}[2m])) by (namespace, pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Output",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Output records",
     "type": "timeseries",
     "description": "Show how much processed records were sent to any outputs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "r/s" } },
     "targets": [
      {
       "expr": "sum(rate(fluentbit_output_proc_records_total{cluster=\"$cluster\", namespace=\"$namespace\"}[2m])) by (namespace, pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Dropped records",
     "type": "timeseries",
     "description": "Show how much records were dropped by output plugin",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum(rate(fluentbit_output_dropped_records_total{cluster=\"$cluster\", namespace=\"$namespace\"}[2m])) by (namespace, pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "description": "Show how much errors occurred during send messages to any outputs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(fluentbit_output_errors_total{cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (namespace, pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Retries",
     "type": "timeseries",
     "description": "Show how much retries FluentBit execute to send messages to any output",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(fluentbit_output_retries_total{cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (namespace, pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Failed retries",
     "type": "timeseries",
     "description": "Show number of abandoned batches because the maximum number of re-tries was reached.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "sum(rate(fluentbit_output_retries_failed_total{cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (namespace, pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Details $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "pod",
   "collapsed": true,
   "panels": [
    {
     "title": "Input bytes/s for $pod",
     "type": "timeseries",
     "description": "Show how much bytes FluentBit read or received by plugin. In legend you can see a plugin name.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(fluentbit_input_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}[1m])",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Output bytes/s for $pod",
     "type": "timeseries",
     "description": "Show how much bytes FluentBit sent to any outputs. In legend you can see a plugin name.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(fluentbit_output_proc_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}[1m])",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Input records/s for $pod",
     "type": "timeseries",
     "description": "Show how much records FluentBit read or received from any sources",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "r/s" } },
     "targets": [
      {
       "expr": "rate(fluentbit_input_records_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}[2m])",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Filter dropped records/s for $pod",
     "type": "timeseries",
     "description": "Show how much records were dropped during processing records in FluentBit. In legend you can see a plugin name.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "r/s" } },
     "targets": [
      {
       "expr": "rate(fluentbit_filter_drop_records_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}[2m])",
       "legendFormat": " {{ name }}"
      }
     ]
    },
    {
     "title": "Output records/s for $pod",
     "type": "timeseries",
     "description": "Show how much processed records were sent to any outputs",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "r/s" } },
     "targets": [
      {
       "expr": "rate(fluentbit_output_proc_records_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}[2m])",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Open files for $pod",
     "type": "timeseries",
     "description": "Show how much files FluentBit open to read logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "idelta(fluentbit_input_files_opened_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}[2m])",
       "legendFormat": "Open files {{ name }}"
      }
     ]
    },
    {
     "title": "Closed/rotated files for $pod",
     "type": "timeseries",
     "description": "Show much files FluentBit closed after complete read logs from these files and files which FluentBit reads were rotated",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "idelta(fluentbit_input_files_closed_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}[2m])",
       "legendFormat": "Closed files {{ name }}"
      },
      {
       "expr": "idelta(fluentbit_input_files_rotated_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}[2m])",
       "legendFormat": "Rotated files {{ name }}"
      }
     ]
    },
    {
     "title": "Filter added records for $pod",
     "type": "timeseries",
     "description": "Show how much records were added with using filters in FluentBit. In legend you can see a plugin name.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "r/s" } },
     "targets": [
      {
       "expr": "rate(fluentbit_filter_add_records_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}[2m])",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Filter emitted records for $pod",
     "type": "timeseries",
     "description": "Show how much records were emitted with using filters in FluentBit.\nThe `Emitter` is an internal FluentBit plugin that allows other components of the pipeline to emit custom records. On this case `rewrite_tag` creates an Emitter instance to use it exclusively to emit records, on that way we can have a granular control of who is emitting what. In legend you can see a plugin name.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "r/s" } },
     "targets": [
      {
       "expr": "rate(fluentbit_filter_emit_records_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}[2m])",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Error/s for $pod",
     "type": "timeseries",
     "description": "Show how much errors occurred during send messages to any outputs. In legend you can see a plugin name.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(fluentbit_output_errors_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}[1m])",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Retries/fails for $pod",
     "type": "timeseries",
     "description": "Show how much retries FluentBit execute to send messages to any output and how much of these retries were failed. In legend you can see a plugin name.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(fluentbit_output_retries_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}[1m])",
       "legendFormat": "Retries {{ name }}"
      },
      {
       "expr": "rate(fluentbit_output_retries_failed_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}[1m])",
       "legendFormat": "Failed retries {{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Parsing health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input vs Output Delta",
     "type": "timeseries",
     "description": "Delta between input records (including multiline) and output records by pod",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum by (pod) (fluentbit_input_records_total)\r\n+ \r\nsum by (pod) (fluentbit_filter_add_records_total{name=~\"multiline.*\"})\r\n- \r\nsum by (pod) (fluentbit_filter_drop_records_total{name=~\"multiline.*\"})\r\n-\r\nsum by (pod) (fluentbit_output_proc_records_total)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Parse Error Total Rate",
     "type": "timeseries",
     "description": "Rate of custom log_to_metrics counter",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "sum by (namespace, pod, container) (\r\n  rate(fluentbit_parse_error_total[$__rate_interval])\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Filter Drop Records Total Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum by (name) (\r\n  rate(fluentbit_filter_drop_records_total[$__rate_interval]) > 0\r\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}