[FILTER]
    Name               modify
    Match_regex        (pods|klog).*
    Condition          Key_exists          klog_date
    Set                parse_format        klog

[FILTER]
    Name               modify
    Match_regex        (pods|klog).*
    Condition          Key_exists          tenant_id
    Condition          Key_exists          thread
    Condition          Key_exists          request_id
    Condition          Key_exists          class
    Condition          Key_does_not_exist  parse_level_unknown
    Set                parse_format        qubership

[FILTER]
    Name               modify
    Match_regex        (pods|klog).*coredns.*
    Condition          Key_exists          module
    Set                parse_format        coredns

[FILTER]
    Name               modify
    Match_regex        pods.*nginx.*
    Condition          Key_exists          method
    Condition          Key_exists          path
    Condition          Key_exists          code
    Set                parse_format        k8s-nginx-ingress

[FILTER]
    Name               modify
    Match_regex        pods.*cassandra.*
    Condition          Key_exists          method
    Set                parse_format        cassandra

[FILTER]
    Name               modify
    Match_regex        pods.*opensearch.*
    Condition          Key_exists          opensearch_node
    Condition          Key_exists          logger
    Set                parse_format        opensearch

[FILTER]
    Name               modify
    Match_regex        pods.*fluentbit.*
    Condition          Key_exists          component
    Set                parse_format        fluentbit

[FILTER]
    Name               modify
    Match_regex        pods.*(mongo.*cnfrs|graylog.*mongo).*
    Condition          Key_exists          component
    Condition          Key_exists          id
    Condition          Key_exists          context
    Set                parse_format        mongodb_structured

[FILTER]
    Name               modify
    Match_regex        pods.*jaeger.*
    Set                parse_format        jaeger

[FILTER]
    Name               modify
    Match_regex        (pods|klog).*
    Condition          Key_does_not_exist  parse_format
    Set                parse_format        unknown
