kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logging-fluentbit-agg-cluster-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logging-fluentbit-aggregator-cluster-role
subjects:
  - kind: ServiceAccount
    name: logging-fluentbit-aggregator
    namespace: logging-service
