kind: Service
apiVersion: v1
metadata:
  name: logging-fluentbit-aggregator
  namespace: {{ .Release.Namespace }}
  labels:
    component: logging-fluentbit-aggregator
{{- if .Values.OpenshiftDeploy }}
    provider: openshift
{{- else }}
    provider: kubernetes
{{- end }}
spec:
  ports:
    - name: logging-fluentbit
      protocol: TCP
      port: 2020
      targetPort: 2020
    - name: log-to-metrics
      protocol: TCP
      port: 2021
      targetPort: 2021
    - name: logging-fluentbit-aggregator
      protocol: TCP
      port: 24224
      targetPort: 24224
  selector:
    name: logging-fluentbit-aggregator
{{- if .Values.OpenshiftDeploy }}
    provider: openshift
{{- else }}
    provider: kubernetes
{{- end }}
  type: ClusterIP
