{{- if .Values.createClusterAdminEntities }}
{{- if .Values.cloudEventsReader.install }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-cloud-events-reader
  labels:
    app.kubernetes.io/name: {{ .Release.Namespace }}-cloud-events-reader
    app.kubernetes.io/component: events-reader
    app.kubernetes.io/part-of: logging
  {{- if .Values.cloudEventsReader.labels }}
    {{- toYaml .Values.cloudEventsReader.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.cloudEventsReader.annotations }}
  annotations:
    {{- toYaml .Values.cloudEventsReader.annotations | nindent 4 }}
  {{- end }}
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: events-reader
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
