{{- if .Values.createClusterAdminEntities }}
{{- if .Values.cloudEventsReader.install }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-cloud-events-reader
  {{- if .Values.cloudEventsReader.annotations }}
  annotations:
    {{- toYaml .Values.cloudEventsReader.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "logging-operator.resourceLabels" (dict "ctx" . "name" (printf "%s-cloud-events-reader" .Release.Namespace) "component" "events-reader") | nindent 4 }}
    {{- if .Values.cloudEventsReader.labels }}
      {{- toYaml .Values.cloudEventsReader.labels | nindent 4 }}
    {{- end }}
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: events-reader
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
