{{- if .Values.cloudEventsReader.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: events-reader
  labels:
    {{- include "logging.labels" (dict "ctx" . "name" "events-reader" "component" "events-reader") | nindent 4 }}
    {{- if .Values.cloudEventsReader.labels }}
    {{- include "logging.extraLabels" (dict "ctx" . "extraLabels" .Values.cloudEventsReader.labels) | nindent 4 }}
    {{- end }}
  {{- if .Values.cloudEventsReader.annotations }}
  annotations:
    {{- toYaml .Values.cloudEventsReader.annotations | nindent 4 }}
  {{- end }}
{{- end }}
