kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-graylog
  labels:
    name: {{ .Release.Namespace }}-graylog
    app.kubernetes.io/name: {{ .Release.Namespace }}-graylog
    app.kubernetes.io/component: graylog
    app.kubernetes.io/part-of: logging
    app.kubernetes.io/managed-by: manually
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}-graylog
subjects:
  - kind: ServiceAccount
    name: logging-graylog
    namespace: logging-service
