kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: graylog-cluster-role
  labels:
    name: graylog-cluster-role
    app.kubernetes.io/name: graylog-cluster-role
    app.kubernetes.io/component: graylog
    app.kubernetes.io/part-of: logging
    app.kubernetes.io/managed-by: manually
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logging-graylog-cluster-role
subjects:
  - kind: ServiceAccount
    name: logging-graylog
    namespace: logging-service
