apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-upgrade-job-50
  namespace: {{ .Release.Namespace }}
  labels: {}
spec:
  backoffLimit: 3
  template:
    metadata:
      labels: {}
    spec:
      restartPolicy: Never
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongo-claim
      containers:
        - name: mongo
          image: {{ .Values.Graylog.MongoDBImage }}
          command:
            - /bin/sh
            - -c
            - |
              mongod --wiredTigerEngineConfigString="cache_size=512M" --fork --syslog
              sleep 15
              mongosh --quiet --eval 'db.adminCommand( { setFeatureCompatibilityVersion: "5.0" } )'
              mongod --shutdown
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: mongodb
              mountPath: /data/db
              readOnly: false
          {{ if not .Values.OpenshiftDeploy }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          {{ end }}
      {{ if not .Values.OpenshiftDeploy }}
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      {{ end }}
