apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-upgrade-job-42
  namespace: {{ .Release.Namespace }}
  labels: {}
spec:
  backoffLimit: 3
  template:
    metadata:
      labels: {}
    spec:
      restartPolicy: Never
      containers:
        - name: mongo
          image: {{ .Values.Graylog.MongoDBUpgrade.MongoDBImage42 }}
          command:
            - /bin/sh
            - -c
            - |
              mongod --wiredTigerEngineConfigString="cache_size=512M" --fork --syslog
              sleep 15
              mongo --quiet --eval 'db.adminCommand( { setFeatureCompatibilityVersion: "4.2" } )'
              mongod --shutdown
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: mongodb
              mountPath: /data/db
              readOnly: false
            - name: tmp
              mountPath: /tmp
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            capabilities:
              drop:
                - ALL
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongo-claim
        - name: tmp
          emptyDir:
            sizeLimit: 100Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
