# This filter generates a Prometheus metric that counts the number of log records
# which failed to be parsed (i.e., records where the "parse_status" field is "failed").
[FILTER]
    name               log_to_metrics
    match_regex        (pods|klog).*
    flush_interval_sec 20
    tag                parse_error_metrics
    metric_mode        counter
    metric_name        parse_error_total
    metric_description Total number of parse errors
    label_field        namespace
    label_field        pod
    label_field        container
    Regex              parse_status ^failed$
# This filter generates a Prometheus metric that counts the number of syn packets sent without response,
# based on log records from calico-node pods.
[FILTER]
    Name                 log_to_metrics
    Match_regex          pods.*calico-node.*
    Flush_interval_sec   20
    Tag                  calico
    Metric_mode          counter
    Metric_name          calico_syn_packets_total
    Metric_Description   Total number of syn packets sent without response
    label_field          src_ip
    label_field          dst_ip
    label_field          src_pod
    label_field          dst_pod
    label_field          src_namespace
    label_field          dst_namespace
    label_field          namespace
    label_field          pod
    label_field          container
    Regex                src_ip ^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$
