# Check if log was parsed by comparing original fields count and final    fields count
[FILTER]
    Name           lua
    Match_regex    (pods|klog).*
    Script         /fluent-bit/etc/count_fields.lua
    Call           second_count_fields

# Try to extract level from log
[FILTER]
    Name           parser
    Match          pods*
    Key_Name       log
    Parser         level_parser_common_keep
    Reserve_Data   On
    Preserve_Key   On

[FILTER]
    Name           modify
    Match          pods*
    Condition      Key_value_matches   logfmt_candidate  true
    Condition      Key_value_matches   parse_status      success
    Set            parse_format        logfmt
    Rename         msg                 short_message
    Rename         time                log_time

[FILTER]
    Name           modify
    Match_regex    pods.*(postgres|patroni|pg).*
    Condition      Key_exists          short_message
    Condition      Key_value_matches   parse_status      success
    Set            parse_format        postgres

[FILTER]
    Name           modify
    Match_regex    pods.*consul.*
    Condition      Key_exists          short_message
    Condition      Key_value_matches   parse_status      success
    Set            parse_format        consul

# Copy content of log field to short_message if short_message doesn't exist
[FILTER]
    Name           modify
    Match_regex    (pods|klog).*
    Copy           log          short_message

# Parse dynamic [key=value] labels if log field exists and parse_status = success
[FILTER]
    Name           lua
    Match          pods*
    Script         /fluent-bit/etc/parse_key_value.lua
    Call           kv_parse

[FILTER]
    Name                         modify
    Match_Regex                  pods.*grafana.*
    Condition Key_value_matches  log /Invalid\susername\sor\spassword|Successful\sLogin|Successful\sLogout|Failed\sto\slook\sup\suser\sbased\son\scookie/
    Set                          nc_audit_label true

[FILTER]
    Name                         modify
    Match_Regex                  pods.*mongo.*
    Condition Key_value_matches  log /ACCESS|CONTROL/
    Set                          nc_audit_label true

[FILTER]
    Name                         modify
    Match                        pods*
    Condition Key_value_matches  log /access-control|PG_SERVICE|database\ssystem\sis|audit_log_type|AUDIT|logType[\":\s\t=]*audit|org\.qubership\.security\.audit.*CEF|org\.qubership\.cloud\.keycloak\.provider.*/
    Set                          nc_audit_label true

[FILTER]
    Name                         modify
    Match                        pods*
    Condition Key_value_matches  parse_status  success
    Condition Key_value_matches  log  ^\[\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[\.,]\d{3}Z?\]\s*\[\s*(?:TRACE|DEBUG|INFO|WARN(?:ING)?|ERROR|FATAL)\s*\]\s*\[\s*request_id\s*=\s*[^]]+\s*\]\s*\[\s*tenant_id\s*=\s*[^]]+\s*\]
    Set                          parse_format     java

[FILTER]
    Name               modify
    Match              pods*
    Condition          Key_value_matches   logfmt_candidate  true
    Condition          Key_exists          msg
    Set                parse_format        logfmt
    Rename             msg                 short_message
    Rename             time                log_time

# Remove extra fields used for validation unconditionally
[FILTER]
    Name                record_modifier
    Match_regex         (pods|klog).*
    Remove_key          orig_field_count
    Remove_key          field_count
    Remove_key          log
    Remove_key          original_log
    Remove_Key          logfmt_candidate
