kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-fluentd
  labels:
    name: {{ .Release.Namespace }}-fluentd
    app.kubernetes.io/name: {{ .Release.Namespace }}-fluentd
    app.kubernetes.io/component: fluentd
    app.kubernetes.io/part-of: logging
    app.kubernetes.io/managed-by: manually
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: logging-fluentd
    namespace: logging-service
