{{- $ctx := . -}}

{{- $authPaths := list }}

{{- if and .Values.fluentd.install .Values.fluentd.output }}
  {{- if and .Values.fluentd.output.loki .Values.fluentd.output.loki.enabled .Values.fluentd.output.loki.auth }}
    {{- $authPaths = append $authPaths (dict "auth" .Values.fluentd.output.loki.auth "default" (printf "%s-fluentd-loki-auth" .Release.Name) "component" "fluentd" "output" "loki") }}
  {{- end }}
  {{- if and .Values.fluentd.output.http .Values.fluentd.output.http.enabled .Values.fluentd.output.http.auth }}
    {{- $authPaths = append $authPaths (dict "auth" .Values.fluentd.output.http.auth "default" (printf "%s-fluentd-http-auth" .Release.Name) "component" "fluentd" "output" "http") }}
  {{- end }}
{{- end }}

{{- if .Values.fluentbit.install }}
  {{- if and .Values.fluentbit.output .Values.fluentbit.output.loki }}
    {{- if and .Values.fluentbit.output.loki.enabled .Values.fluentbit.output.loki.auth }}
      {{- $authPaths = append $authPaths (dict "auth" .Values.fluentbit.output.loki.auth "default" (printf "%s-fluentbit-loki-auth" .Release.Name) "component" "fluentbit" "output" "loki") }}
    {{- end }}
  {{- end }}
  {{- if and .Values.fluentbit.output .Values.fluentbit.output.http }}
    {{- if and .Values.fluentbit.output.http.enabled .Values.fluentbit.output.http.auth }}
      {{- $authPaths = append $authPaths (dict "auth" .Values.fluentbit.output.http.auth "default" (printf "%s-fluentbit-http-auth" .Release.Name) "component" "fluentbit" "output" "http") }}
    {{- end }}
  {{- end }}
  {{- if and .Values.fluentbit.output .Values.fluentbit.output.otel }}
    {{- if and .Values.fluentbit.output.otel.enabled .Values.fluentbit.output.otel.auth }}
      {{- $authPaths = append $authPaths (dict "auth" .Values.fluentbit.output.otel.auth "default" (printf "%s-fluentbit-otel-auth" .Release.Name) "component" "fluentbit" "output" "otel") }}
    {{- end }}
  {{- end }}
  {{- if and .Values.fluentbit.aggregator .Values.fluentbit.aggregator.install .Values.fluentbit.aggregator.output }}
    {{- if and .Values.fluentbit.aggregator.output.loki .Values.fluentbit.aggregator.output.loki.enabled .Values.fluentbit.aggregator.output.loki.auth }}
      {{- $authPaths = append $authPaths (dict "auth" .Values.fluentbit.aggregator.output.loki.auth "default" (printf "%s-fluentbit-aggregator-loki-auth" .Release.Name) "component" "fluentbit-aggregator" "output" "loki") }}
    {{- end }}
    {{- if and .Values.fluentbit.aggregator.output.http .Values.fluentbit.aggregator.output.http.enabled .Values.fluentbit.aggregator.output.http.auth }}
      {{- $authPaths = append $authPaths (dict "auth" .Values.fluentbit.aggregator.output.http.auth "default" (printf "%s-fluentbit-aggregator-http-auth" .Release.Name) "component" "fluentbit-aggregator" "output" "http") }}
    {{- end }}
    {{- if and .Values.fluentbit.aggregator.output.otel .Values.fluentbit.aggregator.output.otel.enabled .Values.fluentbit.aggregator.output.otel.auth }}
      {{- $authPaths = append $authPaths (dict "auth" .Values.fluentbit.aggregator.output.otel.auth "default" (printf "%s-fluentbit-aggregator-otel-auth" .Release.Name) "component" "fluentbit-aggregator" "output" "otel") }}
    {{- end }}
  {{- end }}
{{- end }}

{{- range $path := $authPaths }}
  {{- if (include "logging.output.auth.shouldCreateSecret" $path) }}
    {{- $secretName := include "logging.output.auth.secretName" $path }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "logging.labels" (dict "ctx" $ctx "name" $secretName "component" $path.component) | nindent 4 }}
type: Opaque
data:
    {{- if $path.auth.credentials.username }}
  username: {{ $path.auth.credentials.username | b64enc }}
    {{- end }}
    {{- if $path.auth.credentials.password }}
  password: {{ $path.auth.credentials.password | b64enc }}
    {{- end }}
    {{- if $path.auth.credentials.token }}
  token: {{ $path.auth.credentials.token | b64enc }}
    {{- end }}
  {{- end }}
{{- end }}
