kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
priority: 3
metadata:
  name: logging-graylog
  labels:
    name: logging-graylog
    app.kubernetes.io/name: logging-graylog
    app.kubernetes.io/component: graylog
    app.kubernetes.io/part-of: logging
    app.kubernetes.io/managed-by: manually
allowPrivilegedContainer: false
allowHostDirVolumePlugin: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:logging-service:logging-graylog
defaultAddCapabilities: []
requiredDropCapabilities: []
allowedCapabilities: []
volumes:
  - 'configMap'
  - 'emptyDir'
  - 'hostPath'
  - 'persistentVolumeClaim'
  - 'projected'
  - 'secret'
allowHostNetwork: false
allowHostPorts: false
allowHostPID: false
allowHostIPC: false
readOnlyRootFilesystem: false
