name: Check Tag actions
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name to check'
        required: true
        default: 'v1.0.0'
      check_tag:
        description: 'Check tag existence'
        required: true
        type: boolean
        default: true
      create_tag:
        description: 'Create tag if it does not exist'
        required: true
        type: boolean
        default: true
      delete_tag:
        description: 'Delete tag if it exists'
        required: true
        type: boolean
        default: true
      dry_run:
        description: 'Dry run without making changes'
        type: boolean
        required: true
        default: false


jobs:
  check-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check tag
        uses: nookyo/qubership-workflow-hub/actions/tag-action@main
        with:
          ref: main
          tag-name: "${{ github.event.inputs.tag_name }}"
          check-tag: "${{ github.event.inputs.check_tag }}"
          create-tag: "${{ github.event.inputs.create_tag }}"
          delete-tag: "${{ github.event.inputs.delete_tag }}"
          dry-run: "${{ github.event.inputs.dry_run }}"